# 生产环境配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ps
    username: root
    password: root
mybatis:
  type-aliases-package: com.example.education