spring:
  profiles:
    active: dev
    # 所有环境通用的配置，放在这里
    # 404 交给异常处理器处理
    mvc:
       throw-exception-if-no-handler-found: true
    resources:
       add-mappings: false
#mybatis
mybatis:
  type-aliases-package: com.ps.entity
  mapper-locations: classpath:mapper/*.xml

#mappers 多个接口时逗号隔开
#mapper:
#  mappers: com.ps.core.iMapper
#  not-empty: false
##  identity: MYSQL
